resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astrofrog
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    # PEP8 checks
    - linux: codestyle
      coverage: 'false'

    # Linux builds - test on all supported Matplotlib versions
    - linux: py36-test-mpl30
    - linux: py37-test-mpl31
    - linux: py37-test-mpl32
    - linux: py38-test-mpl33
    - linux: py38-test-mpldev

    # MacOS X and Windows builds - alternative Matplotlib versions
    - windows: py36-test-mpl30
    - macos: py37-test-mpl31
    - windows: py37-test-mpl32
    - macos: py38-test-mpl33
    - windows: py38-test-mpldev

    # Image tests
    - linux: py37-test-mpl30-image
    - linux: py37-test-mpl31-image
