resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astrofrog
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    # PEP8 checks
    - linux: codestyle
      coverage: 'false'

    # Linux builds - test on all supported Matplotlib versions
    - linux: py36-test-mpl30
    - linux: py37-test-mpl31
    - linux: py37-test-mpl32
    - linux: py38-test-mpl33
    - linux: py38-test-mpldev

    # MacOS X and Windows builds - alternative Matplotlib versions
    - windows: py36-test-mpl30
    - macos: py37-test-mpl31
    - windows: py37-test-mpl32
    - macos: py38-test-mpl33
    - windows: py38-test-mpldev

- job: VisualizationMatplotlib
  displayName: Visualization tests
  strategy:
    matrix:
      mpl30:
        toxenv: py37-test-mpl30-image
        image: astropy/image-tests-py37-mpl302:1.10
      mpl31:
        toxenv: py37-test-mpl31-image
        image: astropy/image-tests-py37-mpl311:1.10
  pool:
    vmImage: ubuntu-latest
  container: $[ variables['image'] ]
  steps:
  - script: pip install tox --user
    displayName: Installing tox
  - script: tox
    env:
      TOXENV: $[ variables['toxenv'] ]
