name: CI

on:
  push:
  pull_request:

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      runs-on: |
        linux: ubuntu-latest
      envs: |
        # Code style
        - linux: codestyle

        # Linux builds - test on all supported Matplotlib versions
        - linux: py38-test-mpl33
        - linux: py39-test-mpl34
        - linux: py39-test-mpl35
        - linux: py310-test-mpl36
        - linux: py310-test-mpl37
        - linux: py311-test-mpldev

        # MacOS X and Windows builds - alternative Matplotlib versions
        - windows: py38-test-mpl33
        - macos: py39-test-mpl34
        - windows: py39-test-mpl35
        - macos: py310-test-mpl36
        - windows: py310-test-mpl37
        - windows: py311-test-mpldev

        # Image tests
        - linux: py311-test-mpl38-image

  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs mpl_scatter_density
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
